[package]
name = "gmn_nail"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
gmn_core = { path = "../gmn_core", version = "0.1.0" }
sqlx = { version = "0.7", features = ["runtime-tokio", "postgres"] }
